### ISSUE TITLE
!\!5

### ISSUE THREAD

**Issue by jibanes** [ngn/k#6]
!\\!5
0 0N -9223372036854775806 -9223372036854775803 -9223372036854775799

**Comment by ngn** [comment]
This is correct, given that `x!y` is "residue" and the representation of `0N` is `1L<<63` in C:
```k
 0!1
0N
 (0!1)!2
-9223372036854775806
```
Does `0N!y` do anything special in the original k?

**Comment by ngn** [comment]
for comparison, kona: `0 0 0 0 0`, oK: `0 -0w 0 -0w 0`

**Comment by jibanes** [comment]
right, thanks for clarifying.

**Comment by ngn** [comment]
There already is `1@` for writing to stdout, I don't think `0N!` would be of much use. There might be a good reason for `0N!` but I don't know it yet.
