### ISSUE TITLE
source

### ISSUE THREAD

**Issue by jibanes** [ngn/k#7]
Would you make the source available?

**Comment by ngn** [comment]
Would you if you were me? Why (not)?

**Comment by jibanes** [comment]
The last sourcetree I have is 18-APR-2017, I started to work on it, it's extremely well thought out, readable and concise. I would like to contribute to it and write components necessary to implement a timeseries database.

**Comment by ngn** [comment]
flattery accepted, though "readable" may be too generous for my code :)
